name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: glpi-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the glpi Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u abire --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
